name: Docker Compose Build and Push Workflow

on:
  push:
    branches:
      - master  # Runs when pushing to master
  pull_request:
    branches:
      - master  # Runs when a PR is opened against master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3    

    - name: Extract metadata
      id: meta
      run: |
        SHA_TAG=${{ github.sha }}
        BRANCH_TAG=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')  # Ensure branch names are safe for tags
        REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')  # Normalize repo name
        echo "sha_tag=$SHA_TAG" >> $GITHUB_ENV
        echo "branch_tag=$BRANCH_TAG" >> $GITHUB_ENV
        echo "repo_name=$REPO_NAME" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: ${{ github.event_name != 'pull_request' }}  # Don't push on PRs
        tags: |
          ghcr.io/${{ env.repo_name }}:latest
          ghcr.io/${{ env.repo_name }}:${{ env.sha_tag }}
          ghcr.io/${{ env.repo_name }}:${{ env.branch_tag }}
        file: docker/image/Dockerfile